name: product_list_with_get
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  get: 4.1.4
  get_storage: ^2.0.2
  logger: ^1.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^1.12.2
  json_serializable: ^4.0.3

flutter:
  uses-material-design: true
